# Generated by Django 2.2 on 2019-04-03 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transformations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='root',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
