# Generated by Django 2.2 on 2019-04-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ate_verb', to='words.Word')),
                ('en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_verb', to='words.Word')),
                ('ify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ify_verb', to='words.Word')),
                ('ise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ise_verb', to='words.Word')),
                ('ize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ize_verb', to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_noun', to='words.Word')),
                ('al', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='al_noun', to='words.Word')),
                ('an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='an_noun', to='words.Word')),
                ('ance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ance_noun', to='words.Word')),
                ('ancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ancy_noun', to='words.Word')),
                ('ation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ation_noun', to='words.Word')),
                ('ee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ee_noun', to='words.Word')),
                ('ence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ence_noun', to='words.Word')),
                ('ency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ency_noun', to='words.Word')),
                ('er', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='er_noun', to='words.Word')),
                ('ese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ese_noun', to='words.Word')),
                ('ess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ess_noun', to='words.Word')),
                ('ette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ette_noun', to='words.Word')),
                ('ful', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ful_noun', to='words.Word')),
                ('hood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood_noun', to='words.Word')),
                ('ian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ian_noun', to='words.Word')),
                ('ing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ing_noun', to='words.Word')),
                ('ism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ism_noun', to='words.Word')),
                ('ist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ist_noun', to='words.Word')),
                ('ity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ity_noun', to='words.Word')),
                ('ment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ment_noun', to='words.Word')),
                ('ness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ness_noun', to='words.Word')),
                ('ocracy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocracy_noun', to='words.Word')),
                ('ology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ology_noun', to='words.Word')),
                ('phile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phile_noun', to='words.Word')),
                ('phobe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phobe_noun', to='words.Word')),
                ('phobia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phobia_noun', to='words.Word')),
                ('pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='or_noun', to='words.Word')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_noun', to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Adverb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ly_adverb', to='words.Word')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_adverb', to='words.Word')),
                ('wards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards_adverb', to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('able', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='able_adjective', to='words.Word')),
                ('al', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='al_adjective', to='words.Word')),
                ('an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='an_adjective', to='words.Word')),
                ('centric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centric_adjective', to='words.Word')),
                ('ed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_adjective', to='words.Word')),
                ('ese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ese_adjective', to='words.Word')),
                ('ful', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ful_adjective', to='words.Word')),
                ('ian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ian_adjective', to='words.Word')),
                ('ic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ic_adjective', to='words.Word')),
                ('ical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ical_adjective', to='words.Word')),
                ('ish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ish_adjective', to='words.Word')),
                ('ist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ist_adjective', to='words.Word')),
                ('ive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ive_adjective', to='words.Word')),
                ('less', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='less_adjective', to='words.Word')),
                ('like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_adjective', to='words.Word')),
                ('ly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ly_adjective', to='words.Word')),
                ('ous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ous_adjective', to='words.Word')),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proof_adjective', to='words.Word')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_adjective', to='words.Word')),
                ('y', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y_adjective', to='words.Word')),
            ],
        ),
    ]
